root = "."
tmp_dir = "tmp"
log_dir = "log"
build = "go build"
build_args = []
colors = "true"
clear = "false"
log = "false"
exclude_dir = []
include_ext = ["go"]
exclude_file = []
include_file = []
unhandled = "true"
bin = "tmp/main"
path = "."
delay = 1000
watched_ext = []
poll_interval = 200
force_poll = "false"
poll = []
log_color_main = "cyan"
log_color_build = "yellow"
log_color_runner = "green"
log_color_watcher = "magenta"
runner = "tmp/main"
runner_args = []
runner_env = []
runner_colors = "true"
runner_log_prefix = "app"
runner_log = "true"
runner_log_colors = "true"
runner_log_prefix = "app"
runner_log_flags = "0"
runner_port = "10303"
build_log = "true"
build_log_flags = "0"
